language: php

php:
  - 7.2

before_install:
  - echo | pecl install channel://pecl.php.net/yaml-2.0.0
  - travis_retry make no-dev
  - travis_retry composer dump-autoload
  - cat vendor/composer/autoload_psr4.php

after_success:
  - bash <(curl -s https://codecov.io/bash)
